### ISSUE TITLE
建议写到base

### ISSUE THREAD

**Issue by nullkk** [rain9155/Loading#1]
可以借鉴一下这个思路,在优化一下 , 写个接口,直接继承,每个页面写一次代码有点累赘

/**
 * Created by Liangyao on 2018/3/19 12:38.
 * <p>
 * email: developkk@foxmail.com
 * <p>
 * doc: 对应fragment多种状态下的布局
 */

public class StateLayout extends FrameLayout {

    private View loadingView;
    private View emptyView;
    private View errorView;
    private View contentView;

    public StateLayout(Context context) {
        this(context, null);
    }

    public StateLayout(Context context, AttributeSet attrs) {
        this(context, attrs, 0);
    }

    public StateLayout(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
        init();
    }

    /**
     * 初始化3种布局
     */
    private void init() {

        //加载
        loadingView = View.inflate(getContext(), R.layout.layout_loading, null);
        addView(loadingView);

        //失败
        errorView = View.inflate(getContext(), R.layout.layout_error, null);
        ImageView textView = (ImageView) errorView.findViewById(R.id.ck_btn_reload);
        textView.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                if (listener != null) {
                    listener.onReload();
                }
            }
        });
        addView(errorView);

        //无数据
        emptyView = View.inflate(getContext(), R.layout.layout_empty, null);
        addView(emptyView);

        hideAllView();
    }

    /**
     * 设置ContentView
     *
     * @param view
     */
    public void setContentView(View view) {
        this.contentView = view;
        this.contentView.setVisibility(View.INVISIBLE);
        addView(this.contentView);
    }

    private void hideAllView() {
        loadingView.setVisibility(View.INVISIBLE);
        errorView.setVisibility(View.INVISIBLE);
        emptyView.setVisibility(View.INVISIBLE);

        if (this.contentView != null) {
            this.contentView.setVisibility(View.INVISIBLE);
        }
    }

    /**
     * 显示loadingView
     */
    public void showLoadingView() {
        hideAllView();
        loadingView.setVisibility(View.VISIBLE);
    }

    /**
     * 显示errorView
     */
    public void showErrorView() {
        hideAllView();
        errorView.setVisibility(View.VISIBLE);
    }

    public void showEmptyView() {
        hideAllView();
        emptyView.setVisibility(View.VISIBLE);
    }

    /**
     * 显示contentView
     */
    public void showContentView() {
        hideAllView();
        contentView.setVisibility(View.VISIBLE);
    }

    private OnReloadListener listener;

    public void setOnReloadListener(OnReloadListener listener) {
        this.listener = listener;
    }

    public interface OnReloadListener {
        void onReload();
    }

}

//===base====

 
import android.support.v4.app.Fragment;
import android.content.Context;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.gyf.barlibrary.ImmersionBar;
import com.kejigou.toutiaozhuan.R;
import com.socks.library.KLog;

import butterknife.ButterKnife;
import butterknife.Unbinder;

/**
 * Created by Liangyao on 2018/3/19 12:49.
 * <p>
 * email: developkk@foxmail.com
 * <p>
 * doc: 所有fragment的父类
 */

public abstract class BaseFragment extends Fragment implements StateLayout.OnReloadListener {

    private Unbinder mUnbinder = null;

    public Context mContext;

    public ImmersionBar mImmersionBar;

    /**
     * 复用Fragment的View对象
     */
    protected StateLayout stateLayout;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        if (stateLayout == null) {
            stateLayout = new StateLayout(getActivity());
            int layoutId = getLayoutId();
            View contentView = inflater.inflate(layoutId, null);
            stateLayout.setContentView(contentView);
            //默认显示加载中界面
            stateLayout.showLoadingView();
            stateLayout.setOnReloadListener(this);
           
            loadData();
      

        return stateLayout;
    }

     

    /**
     * [获取全局的Context]
     *
     * @return
     */
    @Override
    public Context getContext() {
        return mContext;
    }

 
    @Override
    public void onReload() {
        stateLayout.showLoadingView();
        loadData();
    }

   

}

**Comment by rain9155** [comment]
对，可以自己把创建StatusView逻辑写到基类中，如果我帮你写，那样我就不知道你具体的页面布局是什么

**Comment by nullkk** [comment]
不是你帮我写😂😂, 是建议可以抽取到公共得地方. 看你demo是每次调用都想要创建. 再提一点(其实没必要在application里面进行初始化,更耗时)
